#version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecodisseny_db
      POSTGRES_USER: ecodisseny_user
      POSTGRES_PASSWORD: ecodisseny_password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecodisseny_user -d ecodisseny_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=161.97.147.142,app.arasmu.net
      - DB_HOST=db
      - DB_NAME=ecodisseny_db
      - DB_USER=ecodisseny_user
      - DB_PASSWORD=ecodisseny_password123
      - DB_PORT=5432
      - STATIC_ROOT=/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn ecodisseny.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
