# Generated by Django 5.2.4 on 2025-08-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('tipo', models.CharField(choices=[('usuario', '👤 Usuario'), ('admin', '🔧 Administrador'), ('dev', '🛠️ Desarrollador'), ('general', '📚 General')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='📚', max_length=50, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('grupos_permitidos', models.ManyToManyField(blank=True, help_text='Si no se especifica, todos los usuarios autenticados tienen acceso', to='auth.group', verbose_name='Grupos con acceso')),
            ],
            options={
                'verbose_name': 'Categoría de Documentación',
                'verbose_name_plural': 'Categorías de Documentación',
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMarkdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='URL amigable')),
                ('archivo_markdown', models.CharField(help_text='Ejemplo: docs/usuario/inicio-rapido.md', max_length=500, verbose_name='Ruta del archivo .md')),
                ('resumen', models.TextField(blank=True, verbose_name='Resumen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('palabras_clave', models.CharField(blank=True, help_text='Separadas por comas', max_length=500, verbose_name='Palabras clave')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.categoriadocumentacion', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria__tipo', 'categoria__orden', 'orden', 'titulo'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de acceso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.documentomarkdown', verbose_name='Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('util', '👍 Útil'), ('no_util', '👎 No útil'), ('incorrecto', '❌ Información incorrecta'), ('falta_info', '❓ Falta información'), ('sugerencia', '💡 Sugerencia')], max_length=20, verbose_name='Tipo')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.documentomarkdown', verbose_name='Documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-fecha'],
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
