# Generated by Django 5.2.4 on 2025-08-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_alter_historialacceso_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomarkdown',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentacion.categoriadocumentacion', verbose_name='Categoría'),
        ),
    ]
