# Generated by Django 5.2.4 on 2026-02-09 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documentacion', '0003_alter_documentomarkdown_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadocumentacion',
            options={'ordering': ['tipo', 'orden', 'nombre'], 'verbose_name': 'Categoria de Documentació', 'verbose_name_plural': 'Categories de Documentació'},
        ),
        migrations.AlterModelOptions(
            name='documentomarkdown',
            options={'ordering': ['categoria__tipo', 'categoria__orden', 'orden', 'titulo'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='historialacceso',
            options={'ordering': ['-fecha_acceso'], 'verbose_name': "Historial d'Accés", 'verbose_name_plural': "Historials d'Accés"},
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='grupos_permitidos',
            field=models.ManyToManyField(blank=True, help_text="Si no s'especifica, tots els usuaris autenticats tenen accés", to='auth.group', verbose_name='Grups amb accés'),
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='icono',
            field=models.CharField(default='📚', max_length=50, verbose_name='Icona'),
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='categoriadocumentacion',
            name='tipo',
            field=models.CharField(choices=[('usuario', '👤 Usuari'), ('admin', '🔧 Administrador'), ('dev', '🛠️ Desenvolupador'), ('general', '📚 General')], max_length=20, verbose_name='Tipus'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='archivo_markdown',
            field=models.CharField(help_text='Exemple: docs/usuari/inici-rapid.md', max_length=500, verbose_name="Ruta de l'arxiu .md"),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documentacion.categoriadocumentacion', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacat'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualitzat'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='palabras_clave',
            field=models.CharField(blank=True, help_text='Separades per comes', max_length=500, verbose_name='Paraules clau'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicat'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='resumen',
            field=models.TextField(blank=True, verbose_name='Resum'),
        ),
        migrations.AlterField(
            model_name='documentomarkdown',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentari'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.documentomarkdown', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='procesado',
            field=models.BooleanField(default=False, verbose_name='Processat'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='tipo',
            field=models.CharField(choices=[('util', '👍 Útil'), ('no_util', '👎 No útil'), ('incorrecte', '❌ Informació incorrecta'), ('falta_info', '❓ Falta informació'), ('suggeriment', '💡 Suggeriment')], max_length=20, verbose_name='Tipus'),
        ),
        migrations.AlterField(
            model_name='feedbackdocumentacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='documentacion.documentomarkdown', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='fecha_acceso',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data d'accés"),
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
    ]
