# Generated by Django 5.2.4 on 2025-08-16 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('pressupostos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarregaHores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hores', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('modif', models.DateTimeField(auto_now=True)),
                ('linia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pressupostos.pressupostlinia')),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pressupostos.pressupost')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.recurso')),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tasca')),
                ('treball', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.treball')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carregues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-creat'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='maestros.recurso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
