# Generated by Django 5.2.4 on 2025-08-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregahores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carregahores',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='carregahores',
            name='tasca',
        ),
        migrations.RemoveField(
            model_name='carregahores',
            name='treball',
        ),
    ]
