# Generated by Django 5.2.4 on 2026-02-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregahores', '0002_remove_carregahores_recurso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
