# Generated by Django 5.2.4 on 2025-07-20 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('projectes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressupost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom del Pressupost')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data del Pressupost')),
                ('observacions', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observacions')),
                ('tancat', models.BooleanField(default=False, verbose_name='Tancat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.clients')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.parroquia')),
                ('projecte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectes.projecte')),
                ('ubicacio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.ubicacio')),
            ],
            options={
                'verbose_name': 'Pressupost',
                'verbose_name_plural': 'Pressupostos',
            },
        ),
        migrations.CreateModel(
            name='PressupostLinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('quantitat', models.IntegerField()),
                ('preu_tancat', models.BooleanField(blank=True, null=True)),
                ('cost_tancat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('increment_hores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hores_totals', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost_hores', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost_hores_totals', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('benefici', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.hores')),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='linies', to='pressupostos.pressupost')),
                ('recurs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.recurso')),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.tasca')),
                ('treball', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.treball')),
            ],
            options={
                'verbose_name': 'Línia de Pressupost',
                'verbose_name_plural': 'Línies de Pressupost',
            },
        ),
        migrations.CreateModel(
            name='PressupostPDFVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('arxiu', models.FileField(upload_to='media/pdfs_pressupostos/')),
                ('data_generat', models.DateTimeField(auto_now_add=True)),
                ('generat_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pressupost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_versions', to='pressupostos.pressupost')),
            ],
            options={
                'verbose_name': 'Versió PDF del Pressupost',
                'verbose_name_plural': 'Versions PDF dels Pressupostos',
                'ordering': ['-version'],
                'unique_together': {('pressupost', 'version')},
            },
        ),
    ]
