# Generated by Django 5.2.4 on 2026-02-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_clients_parroquia_alter_clients_poblacio_and_more'),
        ('pressupostos', '0001_initial'),
        ('projectes', '0002_alter_projecte_client_alter_projecte_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressupost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.clients'),
        ),
        migrations.AlterField(
            model_name='pressupost',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.parroquia'),
        ),
        migrations.AlterField(
            model_name='pressupost',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectes.projecte'),
        ),
        migrations.AlterField(
            model_name='pressupost',
            name='ubicacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.ubicacio'),
        ),
        migrations.AlterField(
            model_name='pressupostlinia',
            name='hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.hores'),
        ),
        migrations.AlterField(
            model_name='pressupostlinia',
            name='recurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.recurso'),
        ),
        migrations.AlterField(
            model_name='pressupostlinia',
            name='tasca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tasca'),
        ),
        migrations.AlterField(
            model_name='pressupostlinia',
            name='treball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.treball'),
        ),
        migrations.AlterField(
            model_name='pressupostpdfversion',
            name='arxiu',
            field=models.FileField(upload_to='pdfs_pressupostos/'),
        ),
    ]
