# Generated by Django 5.2.4 on 2025-07-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressupostos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressupostlinia',
            name='pressupost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='pressupostos.pressupost'),
        ),
    ]
