# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pressupostos", "0002_alter_pressupost_client_alter_pressupost_parroquia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressupostlinia",
            name="aplicar_increment_hores",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pressupostlinia",
            name="aplicar_cost_hores",
            field=models.BooleanField(default=True),
        ),
    ]
