# Generated by Django 5.2.4 on 2025-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressupostos', '0002_alter_pressupostlinia_pressupost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressupostpdfversion',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='Contingut HTML generat'),
        ),
    ]
