# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pressupostos", "0003_pressupostlinia_aplicar_increment_hores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressupost",
            name="default_aplicar_cost_hores",
            field=models.BooleanField(default=True, verbose_name="Per defecte: aplicar cost hores"),
        ),
        migrations.AddField(
            model_name="pressupost",
            name="default_aplicar_increment_hores",
            field=models.BooleanField(default=True, verbose_name="Per defecte: aplicar increment hores"),
        ),
    ]
