# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pressupostos", "0004_pressupost_default_aplicar_increment_hores_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressupost",
            options={
                "permissions": (("view_hores_report", "Pot veure l'informe d'hores previstes vs reals"),),
                "verbose_name": "Pressupost",
                "verbose_name_plural": "Pressupostos",
            },
        ),
    ]
