# Generated by Django 5.2.4 on 2026-03-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pressupostos", "0006_alter_pressupost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressupost",
            options={
                "permissions": (
                    ("view_hores_report", "Pot veure l'informe d'hores previstes vs reals"),
                    ("view_rentabilitat_report", "Pot veure l'informe de rentabilitat per pressupost"),
                    ("view_productivitat_report", "Pot veure l'informe de productivitat per recurs"),
                ),
                "verbose_name": "Pressupost",
                "verbose_name_plural": "Pressupostos",
            },
        ),
    ]
