# Generated by Django 5.2.4 on 2025-08-16 13:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Departament Client')),
            ],
            options={
                'verbose_name': 'Departament Client',
                'verbose_name_plural': 'Departaments Clients',
            },
        ),
        migrations.CreateModel(
            name='Hores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('hores', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Hores',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('parroquia', models.CharField(max_length=100, verbose_name='Parròquia')),
            ],
            options={
                'verbose_name': 'Parròquia',
                'verbose_name_plural': 'Parròquies',
            },
        ),
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('tasca', models.CharField(max_length=100)),
                ('observacions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tasca',
                'verbose_name_plural': 'Tasques',
            },
        ),
        migrations.CreateModel(
            name='TipusRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('tipus', models.CharField(max_length=100, verbose_name='Tipus Recurs')),
            ],
            options={
                'verbose_name': 'Tipus de Recurs',
                'verbose_name_plural': 'Tipus de Recursos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('ubicacio', models.CharField(max_length=100, verbose_name='Ubicació')),
            ],
            options={
                'verbose_name': 'Ubicació',
                'verbose_name_plural': 'Ubicacions',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom_client', models.CharField(max_length=100, verbose_name='Nom del Client')),
                ('rao_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raó Social')),
                ('nrt', models.CharField(blank=True, max_length=100, null=True, verbose_name='NRT')),
                ('carrer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrer')),
                ('numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('escala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escala')),
                ('pis', models.IntegerField(blank=True, null=True, verbose_name='Pis')),
                ('porta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porta')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telèfon')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correu electrònic')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.parroquia', verbose_name='Parròquia')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='PersonaContactClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom_contacte', models.CharField(max_length=100, verbose_name='Contacte Client')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telèfon')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.clients', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contacte Client',
                'verbose_name_plural': 'Contactes Client',
            },
        ),
        migrations.CreateModel(
            name='Poblacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('poblacio', models.CharField(max_length=100, verbose_name='Població')),
                ('codi_postal', models.CharField(max_length=100, verbose_name='Codi Postal')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.parroquia', verbose_name='Parròquia')),
            ],
            options={
                'verbose_name': 'Població',
                'verbose_name_plural': 'Poblacions',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='poblacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.poblacio', verbose_name='Població'),
        ),
        migrations.CreateModel(
            name='TasquesTreball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('observacions', models.CharField(blank=True, max_length=300, null=True)),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.tasca')),
            ],
            options={
                'verbose_name': 'Treball - Tasca',
                'verbose_name_plural': 'Treballs - Tasques',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('preu_tancat', models.IntegerField(verbose_name='Preu Tancat')),
                ('preu_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preu Hora')),
                ('tipus_recurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.tipusrecurso')),
            ],
            options={
                'verbose_name': 'Recurs',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Treball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.CharField(max_length=100, verbose_name='Descripció')),
                ('tasques', models.ManyToManyField(related_name='treballs', through='maestros.TasquesTreball', to='maestros.tasca')),
            ],
            options={
                'verbose_name': 'Treball',
                'verbose_name_plural': 'Treballs',
            },
        ),
        migrations.AddField(
            model_name='tasquestreball',
            name='treball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.treball'),
        ),
        migrations.CreateModel(
            name='Desplacament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('increment_hores', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Increment Hores')),
                ('observacions', models.TextField(blank=True, null=True)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.parroquia')),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.tasca')),
                ('ubicacio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.ubicacio')),
            ],
            options={
                'verbose_name': 'Desplaçament',
                'verbose_name_plural': 'Desplaçaments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tasquestreball',
            unique_together={('tasca', 'treball')},
        ),
    ]
