# Generated by Django 5.2.4 on 2026-02-09 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
        ('carregahores', '0003_delete_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.parroquia', verbose_name='Parròquia'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='poblacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.poblacio', verbose_name='Població'),
        ),
        migrations.AlterField(
            model_name='desplacament',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.parroquia'),
        ),
        migrations.AlterField(
            model_name='desplacament',
            name='tasca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tasca'),
        ),
        migrations.AlterField(
            model_name='desplacament',
            name='ubicacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.ubicacio'),
        ),
        migrations.AlterField(
            model_name='personacontactclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='poblacio',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.parroquia', verbose_name='Parròquia'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipus_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.tipusrecurso'),
        ),
        migrations.AlterField(
            model_name='tasquestreball',
            name='tasca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.tasca'),
        ),
        migrations.AlterField(
            model_name='tasquestreball',
            name='treball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.treball'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PerfilUsuario',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='maestros.recurso')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': "Perfil d'Usuari",
                        'verbose_name_plural': "Perfils d'Usuaris",
                    },
                ),
            ],
            # No database operations needed, the table already exists
            database_operations=[],
        ),
    ]
