# Generated by Django 5.2.4 on 2026-02-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_clients_parroquia_alter_clients_poblacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='nom_client',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom del Client'),
        ),
    ]
