# Generated by Django 5.2.4 on 2025-07-20 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_modificacio', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom del Projecte')),
                ('data_peticio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Petició')),
                ('observacions', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Observacions')),
                ('tancat', models.BooleanField(default=False, verbose_name='Tancat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.clients', verbose_name='Client')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.departamentclient', verbose_name='Departament Client')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.parroquia', verbose_name='Parròquia')),
                ('persona_contacte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.personacontactclient', verbose_name='Persona Contacte')),
                ('ubicacio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.ubicacio', verbose_name='Ubicació')),
            ],
            options={
                'verbose_name': 'Projecte',
                'verbose_name_plural': 'Projectes',
            },
        ),
    ]
