# Generated by Django 5.2.4 on 2026-02-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_clients_parroquia_alter_clients_poblacio_and_more'),
        ('projectes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.departamentclient', verbose_name='Departament Client'),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.parroquia', verbose_name='Parròquia'),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='persona_contacte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.personacontactclient', verbose_name='Persona Contacte'),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='ubicacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.ubicacio', verbose_name='Ubicació'),
        ),
    ]
